//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL_WPF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class movement_of_goodsEntities : DbContext
    {
        public movement_of_goodsEntities()
            : base("name=movement_of_goodsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<заказы> заказы { get; set; }
        public virtual DbSet<контрагенты> контрагенты { get; set; }
        public virtual DbSet<поставщики> поставщики { get; set; }
        public virtual DbSet<склад> склад { get; set; }
    }
}
