//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class заказы
    {
        public string ттн { get; set; }
        public string код_товара { get; set; }
        public string код_поставщика { get; set; }
        public string наименование_поставщика { get; set; }
        public string код_контрагента { get; set; }
        public string наименование_контрагента { get; set; }
        public string наименование_товара { get; set; }
        public string еденицы_измерения { get; set; }
        public Nullable<int> цена_за_еденицу_бел_руб { get; set; }
        public string срок_гарантии { get; set; }
        public Nullable<double> количество_заказанного { get; set; }
        public Nullable<bool> оплачено { get; set; }
        public string вид_оплаты { get; set; }
        public string код_заказа { get; set; }
        public Nullable<System.DateTime> дата_заказа { get; set; }
        public byte[] upsize_ts { get; set; }
    
        public virtual контрагенты контрагенты { get; set; }
        public virtual склад склад { get; set; }
    }
}
