//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class контрагенты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public контрагенты()
        {
            this.заказы = new HashSet<заказы>();
        }
    
        public string код_контрагента { get; set; }
        public string наименование { get; set; }
        public string адрес { get; set; }
        public string телефон { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<заказы> заказы { get; set; }
    }
}
