//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class поставщики
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public поставщики()
        {
            this.склад = new HashSet<склад>();
        }
    
        public string код_поставки { get; set; }
        public string код_поставщика { get; set; }
        public string наименование { get; set; }
        public string адрес { get; set; }
        public string телефон { get; set; }
        public string код_товара { get; set; }
        public string наименование_товара { get; set; }
        public string еденицы_измерения { get; set; }
        public Nullable<int> цена_за_еденицу_бел_руб { get; set; }
        public string срок_гарантии { get; set; }
        public Nullable<int> кол_во_поставляемого { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<склад> склад { get; set; }
    }
}
